"use client"

import { saveProfileAction } from "@/app/(app)/settings/actions"
import { FormError } from "@/components/forms/error"
import { FormAvatar, FormInput, FormTextarea } from "@/components/forms/simple"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { Tenant, User } from "@/prisma/client"
import { CircleCheckBig } from "lucide-react"
import { useActionState } from "react"

export default function ProfileSettingsForm({ user }: { user: User & { tenant: Tenant } }) {
  const [saveState, saveAction, pending] = useActionState(saveProfileAction, null)

  return (
    <div className="space-y-8">
      <form action={saveAction} className="space-y-8">
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Your LedgerNest Profile</h3>
          <FormAvatar
            title="Avatar"
            name="avatar"
            className="w-24 h-24"
            defaultValue={user.avatar ? user.avatar + "?" + user.id : ""}
          />
          <FormInput title="Account Name" name="name" defaultValue={user.name || ""} />
          <div className="flex flex-row items-center gap-4">
            <Button type="submit" disabled={pending}>
              {pending ? "Saving..." : "Save"}
            </Button>
            {saveState?.success && (
              <p className="text-green-500 flex flex-row items-center gap-2">
                <CircleCheckBig />
                Saved!
              </p>
            )}
          </div>
        </div>

        <Separator />

        <div className="space-y-4">
          <div className="space-y-1">
            <h3 className="text-lg font-semibold">Business details</h3>
            <p className="text-sm text-muted-foreground">
              Shared across the workspace and used on invoices generated by any member.
            </p>
          </div>
          <FormInput
            title="Business Name"
            name="businessName"
            placeholder="Acme Inc."
            defaultValue={user.tenant.businessName ?? ""}
          />
          <FormTextarea
            title="Business Address"
            name="businessAddress"
            placeholder="Street, City, State, Zip Code, Country, Tax ID"
            defaultValue={user.tenant.businessAddress ?? ""}
          />
          <FormTextarea
            title="Bank Details"
            name="businessBankDetails"
            placeholder="Bank Name, Account Number, BIC, IBAN, details of payment, etc."
            defaultValue={user.tenant.businessBankDetails ?? ""}
          />
          <FormAvatar
            title="Business Logo"
            name="businessLogo"
            className="w-52 h-52"
            defaultValue={user.tenant.businessLogo ?? ""}
          />
        </div>

        <div className="flex flex-row items-center gap-4">
          <Button type="submit" disabled={pending}>
            {pending ? "Saving..." : "Save"}
          </Button>
          {saveState?.success && (
            <p className="text-green-500 flex flex-row items-center gap-2">
              <CircleCheckBig />
              Saved!
            </p>
          )}
        </div>

        {saveState?.error && <FormError>{saveState.error}</FormError>}
      </form>
    </div>
  )
}
