/**
 * Content for the demo workspace. Everything here is fictional but shaped like
 * a real small business's books, so every screen in the product has something
 * meaningful to show.
 */

export const DEMO_BUSINESS = {
  name: "Northwind Studio",
  address: "Northwind Studio GmbH\nGneisenaustraße 12\n10961 Berlin, Germany\nVAT ID: DE311204884",
  bankDetails: "Berliner Handelsbank\nIBAN: DE89 3704 0044 0532 0130 00\nBIC: COBADEFFXXX\nRef: invoice number",
}

export const DEMO_PROJECTS = [
  { code: "client-work", name: "Client Work", color: "#2563eb", llm_prompt: "billable client engagements" },
  { code: "product", name: "Product R&D", color: "#7c3aed", llm_prompt: "internal product development" },
  { code: "operations", name: "Operations", color: "#0f766e", llm_prompt: "running the studio day to day" },
  { code: "marketing", name: "Marketing", color: "#db2777", llm_prompt: "campaigns, content and events" },
]

export const DEMO_FIELDS = [
  {
    code: "vat_rate",
    name: "VAT Rate",
    type: "string",
    llm_prompt: "VAT or sales tax percentage shown on the document",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "payment_method",
    name: "Payment Method",
    type: "string",
    llm_prompt: "card, bank transfer, cash, direct debit",
    isVisibleInList: true,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "cost_center",
    name: "Cost Center",
    type: "string",
    llm_prompt: "internal cost center or department",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: true,
  },
]

export type DemoTransactionTemplate = {
  name: string
  merchant: string
  description: string
  categoryCode: string
  projectCode: string
  type: "income" | "expense"
  /** Amount in major units; converted to cents when seeded. */
  amount: number
  currencyCode: string
  /** Months in which this line recurs; 0 = current month, 11 = eleven months ago. */
  monthsAgo: number[]
  paymentMethod: string
  vatRate: string
  costCenter: string
}

export const DEMO_TRANSACTIONS: DemoTransactionTemplate[] = [
  {
    name: "Retainer — Halden & Co",
    merchant: "Halden & Co",
    description: "Monthly design retainer, 40 hours",
    categoryCode: "invoice",
    projectCode: "client-work",
    type: "income",
    amount: 6400,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Bank transfer",
    vatRate: "19%",
    costCenter: "Revenue",
  },
  {
    name: "Website rebuild — Kestrel Labs",
    merchant: "Kestrel Labs",
    description: "Phase 2 delivery milestone",
    categoryCode: "invoice",
    projectCode: "client-work",
    type: "income",
    amount: 11500,
    currencyCode: "EUR",
    monthsAgo: [1, 4, 7, 10],
    paymentMethod: "Bank transfer",
    vatRate: "19%",
    costCenter: "Revenue",
  },
  {
    name: "Brand sprint — Volta Mobility",
    merchant: "Volta Mobility",
    description: "Two-week brand identity sprint",
    categoryCode: "invoice",
    projectCode: "client-work",
    type: "income",
    amount: 8900,
    currencyCode: "USD",
    monthsAgo: [2, 6, 9],
    paymentMethod: "Bank transfer",
    vatRate: "0%",
    costCenter: "Revenue",
  },
  {
    name: "Studio rent",
    merchant: "Kreuzberg Werkhof",
    description: "Studio space, 84 m²",
    categoryCode: "rental",
    projectCode: "operations",
    type: "expense",
    amount: 2150,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Direct debit",
    vatRate: "19%",
    costCenter: "Facilities",
  },
  {
    name: "Payroll",
    merchant: "Northwind Studio Payroll",
    description: "Salaries for 4 employees",
    categoryCode: "salary",
    projectCode: "operations",
    type: "expense",
    amount: 18600,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Bank transfer",
    vatRate: "0%",
    costCenter: "People",
  },
  {
    name: "Figma Organization",
    merchant: "Figma",
    description: "12 editor seats",
    categoryCode: "online",
    projectCode: "product",
    type: "expense",
    amount: 540,
    currencyCode: "USD",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Card ···4417",
    vatRate: "0%",
    costCenter: "Tooling",
  },
  {
    name: "Cloud hosting",
    merchant: "Hetzner Online",
    description: "Dedicated servers and object storage",
    categoryCode: "online",
    projectCode: "product",
    type: "expense",
    amount: 312,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Tooling",
  },
  {
    name: "Business insurance",
    merchant: "Allianz",
    description: "Professional indemnity, annual premium",
    categoryCode: "insurance",
    projectCode: "operations",
    type: "expense",
    amount: 1840,
    currencyCode: "EUR",
    monthsAgo: [8],
    paymentMethod: "Direct debit",
    vatRate: "0%",
    costCenter: "Risk",
  },
  {
    name: "Team offsite — Leipzig",
    merchant: "Deutsche Bahn",
    description: "Rail tickets for the quarterly offsite",
    categoryCode: "travel",
    projectCode: "operations",
    type: "expense",
    amount: 486,
    currencyCode: "EUR",
    monthsAgo: [3, 9],
    paymentMethod: "Card ···4417",
    vatRate: "7%",
    costCenter: "People",
  },
  {
    name: "Client lunch",
    merchant: "Restaurant Nobelhart",
    description: "Kickoff lunch with Kestrel Labs",
    categoryCode: "food",
    projectCode: "client-work",
    type: "expense",
    amount: 214,
    currencyCode: "EUR",
    monthsAgo: [1, 5, 8, 11],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Sales",
  },
  {
    name: "Conference tickets — Config",
    merchant: "Config Conference",
    description: "Two tickets, design systems track",
    categoryCode: "events",
    projectCode: "marketing",
    type: "expense",
    amount: 980,
    currencyCode: "USD",
    monthsAgo: [5],
    paymentMethod: "Card ···4417",
    vatRate: "0%",
    costCenter: "Growth",
  },
  {
    name: "LinkedIn campaign",
    merchant: "LinkedIn Ads",
    description: "Lead generation campaign, Q3",
    categoryCode: "ads",
    projectCode: "marketing",
    type: "expense",
    amount: 1250,
    currencyCode: "EUR",
    monthsAgo: [2, 3, 4],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Growth",
  },
  {
    name: "MacBook Pro M4",
    merchant: "Apple Store Berlin",
    description: "Workstation for new designer",
    categoryCode: "tools",
    projectCode: "operations",
    type: "expense",
    amount: 3299,
    currencyCode: "EUR",
    monthsAgo: [6],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Equipment",
  },
  {
    name: "Mobile and internet",
    merchant: "Vodafone Business",
    description: "Studio fibre and 5 mobile lines",
    categoryCode: "communication",
    projectCode: "operations",
    type: "expense",
    amount: 189,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Direct debit",
    vatRate: "19%",
    costCenter: "Facilities",
  },
  {
    name: "Electricity",
    merchant: "Vattenfall",
    description: "Studio electricity",
    categoryCode: "utility_bills",
    projectCode: "operations",
    type: "expense",
    amount: 268,
    currencyCode: "EUR",
    monthsAgo: [0, 2, 4, 6, 8, 10],
    paymentMethod: "Direct debit",
    vatRate: "19%",
    costCenter: "Facilities",
  },
  {
    name: "Office supplies",
    merchant: "Modulor",
    description: "Paper, pens, printer toner",
    categoryCode: "office",
    projectCode: "operations",
    type: "expense",
    amount: 143,
    currencyCode: "EUR",
    monthsAgo: [1, 4, 7, 10],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Facilities",
  },
  {
    name: "Accounting and payroll services",
    merchant: "Steuerkanzlei Bergmann",
    description: "Monthly bookkeeping and payroll filing",
    categoryCode: "fees",
    projectCode: "operations",
    type: "expense",
    amount: 690,
    currencyCode: "EUR",
    monthsAgo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    paymentMethod: "Bank transfer",
    vatRate: "19%",
    costCenter: "Admin",
  },
  {
    name: "Design systems course",
    merchant: "Interaction Institute",
    description: "Professional development for the team",
    categoryCode: "education",
    projectCode: "product",
    type: "expense",
    amount: 1450,
    currencyCode: "EUR",
    monthsAgo: [7],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "People",
  },
  {
    name: "Conference swag",
    merchant: "Printful",
    description: "Stickers and tote bags",
    categoryCode: "swag",
    projectCode: "marketing",
    type: "expense",
    amount: 412,
    currencyCode: "EUR",
    monthsAgo: [4],
    paymentMethod: "Card ···4417",
    vatRate: "19%",
    costCenter: "Growth",
  },
  {
    name: "Open source donation",
    merchant: "Open Collective",
    description: "Sponsoring the tools we build on",
    categoryCode: "donations",
    projectCode: "product",
    type: "expense",
    amount: 300,
    currencyCode: "USD",
    monthsAgo: [0, 3, 6, 9],
    paymentMethod: "Card ···4417",
    vatRate: "0%",
    costCenter: "Community",
  },
]

/** Receipts waiting in the Unsorted inbox, rendered as real image files. */
export const DEMO_UNSORTED_RECEIPTS = [
  {
    merchant: "Bergblick Kaffeerösterei",
    lines: [
      ["2x Espresso beans 1kg", "38.00"],
      ["Filter papers", "6.40"],
      ["Oat milk 12x", "18.90"],
    ],
    total: "63.30",
    currency: "EUR",
    vat: "19%",
    daysAgo: 2,
  },
  {
    merchant: "Papierwerk Berlin",
    lines: [
      ["Sketchbooks A4 (10)", "84.00"],
      ["Pigment markers set", "129.50"],
    ],
    total: "213.50",
    currency: "EUR",
    vat: "19%",
    daysAgo: 4,
  },
  {
    merchant: "Nordwind Coworking",
    lines: [
      ["Day passes (6)", "180.00"],
      ["Meeting room 3h", "75.00"],
    ],
    total: "255.00",
    currency: "EUR",
    vat: "19%",
    daysAgo: 6,
  },
  {
    merchant: "Uber",
    lines: [
      ["Airport → Studio", "42.60"],
      ["Wait time", "3.20"],
    ],
    total: "45.80",
    currency: "EUR",
    vat: "7%",
    daysAgo: 9,
  },
  {
    merchant: "Adobe",
    lines: [["Creative Cloud — 4 seats", "239.96"]],
    total: "239.96",
    currency: "USD",
    vat: "0%",
    daysAgo: 12,
  },
  {
    merchant: "Deutsche Post",
    lines: [
      ["Parcel shipping (4)", "27.80"],
      ["Registered mail", "5.55"],
    ],
    total: "33.35",
    currency: "EUR",
    vat: "19%",
    daysAgo: 15,
  },
]

export const DEMO_SETTINGS: Record<string, string> = {
  default_currency: "EUR",
  default_project: "operations",
  default_category: "office",
  default_type: "expense",
  is_welcome_message_hidden: "false",
}
